### ISSUE TITLE
Receptors features not showing up for right hemisphere hOc1

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1000]
In the tutorial yesterday we realized that when searching for receptor densities for hOc1 in the current live version of siibra-explorer, only the left hemisphere brings up the „real“ receptor feature. In hOc1 right, it just appears as an ebrains dataset feature, not a as receptor feature with fingerprints etc.

In siibra-python,  I get a receptor feature for both left and right hemispheres, so I guess the bug is in the API or explorer:
```python
import siibra
atlas = siibra.atlases['human‘]
siibra.get_features(atlas.get_region('hoc1 left'),'receptor’)
# -> one feature delivered
siibra.get_features(atlas.get_region('hoc1 right'),'receptor’)
# -> same feature delivered, but not found in siibra-explorer
```

**Comment by fsdavid** [comment]
Related to https://github.com/FZJ-INM1-BDA/siibra-api/issues/41

**Comment by xgui3783** [comment]
can no longer reproduce as of 2.7.6.

I suspect this is an issue, which is a combination of

- poisoned cache
- siibra-api acting up
