### ISSUE TITLE
Names of sulci missing in MNI152 3D view

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1001]
The MNI152 space 3D view shows meshes of principal sulci. When hovering them, names are technical ("auxmesh .xxyyo"). Expected behavior would be to see their real names. As an example, it would be great to be able to find the central sulcus by hovering over the 3D view.

**Comment by xgui3783** [comment]
hovering auxiliary mesh no longer show text

re: show more complex names e.g. central sulcus - potentially possible, but needs the data to be updated (e.g. break up the sulci into components, give each a name, etc etc)
