### ISSUE TITLE
from support email feedback: allow selection of multiple regions

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#1008]
(support ticket #8753)

possibly related to two separated, but related feature requests:
- [ ] select super structure
- [ ] select arbitrary structures on (potentially) different branches

**Comment by xgui3783** [comment]
More detail:

Able to visualise spatial relationships between two regions and their spatial relationship.

visualise the connection between the regions (require support from siibra-python and siibra-api)

**Comment by dickscheid** [comment]
I second that his is an important next feature. siibra-python can handle multi-region selections in principle already, but it is not yet obviously modelled on the surface.

**Comment by xgui3783** [comment]
also requested by @ch-schiffer

**Comment by dickscheid** [comment]
has been merged into new issue
