### ISSUE TITLE
modify region hierarchy view 

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#1010]
Expected behavior:
- Search for a region by name. In general, the resulting filtered tree will show both parent nodes of the regiontree (e.g. regions with subregions, and no explicit maps), as well as leaves (e.g. regions with maps which have no further children)
- for parent nodes, clicking on them should open the subtree to find actual maps
- for leave nodes, clicking on them would select.

- When collapsing a subtree, and then expanding it again, I would expect the expansion to go level by level:
-- after collapsing a subtree, I see only its root node (this is the case already)
-- when clicking the root node again, it expands only to the next level (currently; it will expand down to the lowest level)

This is important to be able to go through the tree level by level. In the current version, it is almost impossible to produce a partially collapsed tree.

**Comment by fsdavid** [comment]
Into the https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1009 PR. 
1 - UI is modified to make it style of the viewer (Material design)
2 - Now it is easy to understand which regions are selectable 
3 - Selectable regions are obvious
4 - Now it is not a problem for sensor devices to use selection and navigator to region

Problem:
1 - `Navigate` buttons need to be added only when a position is available, but currently we do not have that info.

**Comment by xgui3783** [comment]
this issue is rather old, but:

1/ navigate button -> no longer exist. in hierarchy mode, single click leaf will select/deselect the region. branch -> single click will collapse/expand the leaf
2/ we have been asked to restore the ability to select branch

my recommendation is closing this issue. reopen if the issue persist. 

ping @fsdavid

**Comment by xgui3783** [comment]
> Search for a region by name. In general, the resulting filtered tree will show both parent nodes of the regiontree (e.g. regions with subregions, and no explicit maps), as well as leaves (e.g. regions with maps which have no further children)

as of v2.14.0, this is now the case 

> for parent nodes, clicking on them should open the subtree to find actual maps
> for leave nodes, clicking on them would select.

this is already the case begin with

> when clicking the root node again, it expands only to the next level

not intended.
