### ISSUE TITLE
Low contrast coloring of DiFuMo maps

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1013]
The colormap for DiFuMo parcellation maps seems to have changed compared to previous versions. For some granularities, the contrast is too low so that regions are difficult to distinguish:

![grafik](https://user-images.githubusercontent.com/1436846/132292550-9ba83012-9420-49ce-b105-209df6e60f0b.png)

The effect seems to be stronger for low-granularity maps like 64dim and 128dim - maybe the colormap needs to be stretched between minimum and maximum label index?

**Comment by xgui3783** [comment]
tracked in https://github.com/FZJ-INM1-BDA/siibra-explorer/issues/1123
