### ISSUE TITLE
Regional features list too large when having only few entries

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1014]
The list of regional features seems to have a minimum fixed size, which gives a confusing view when only few or especially no features are found for a region:
![grafik](https://user-images.githubusercontent.com/1436846/132295435-04a76292-9f07-40d6-9d68-8b732811b1b0.png)

In particular, when no feature is ofound, the impression is that the system might still be loading to fill the empty space. I would suggest not to have a minimum height, and also to introduce a short info text if no features are available so it is clear that the system has performed a query.

**Comment by xgui3783** [comment]
regional feature is redesigned. this issue is no longer relevant.
