### ISSUE TITLE
Regional datasets missing in mouse brain 

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1016]
It seems that the mouse brain is not delivering all the regional data features available. 

In siibra-python (0.2a2), for example, 

```python
import siibra
atlas = siibra.atlases['mouse']
r = atlas.get_region('striatum dorsal')
for f in siibra.get_features(r,'ebrains'):
    print(f.name)
```

gives
```
https://nexus.humanbrainproject.org/v0/data/minds/core/dataset/v1.0.0/e174a987-744f-43d2-8b43-3c8cb0a5c13c
Characterization of striatal neurons in Parkinson’s disease patients and healthy individuals using scRNA-seq
https://nexus.humanbrainproject.org/v0/data/minds/core/dataset/v1.0.0/a4d76158-ba11-4f13-aa4b-49d7c7652ce3
In-depth characterization of striatal neurons in non-human primates using single-cell RNA-seq
```

while selecting the same region in siibra-explorer yields an empty list in the sidepanel.

**Comment by xgui3783** [comment]
related to https://github.com/FZJ-INM1-BDA/siibra-python/issues/85

whilst siibra-stable does not use 0.2a2, but 0.1a8 instead, on my local machine, with the correct token, I could fetch the datasets :

```bash
curl 'http://localhost:5000/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F2/parcellations/minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F39a1384b-8413-4d27-af8d-22432225401f/regions/Striatum%20dorsal%20region%20/features/EbrainsRegionalDataset' | jq 'length'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3922  100  3922    0     0  1276k      0 --:--:-- --:--:-- --:--:-- 1915k
18
```

Last update I heard was @skoehnen was asking Oli to approve a oidc client to resume the programmatic generation of valid access tokens, which should allow for the queries to resume functioning.

**Comment by dickscheid** [comment]
@marcenko @xgui3783 any update here? It is important that the EBRAINS regional datasets are listed reliably for all species. I suggest we have a brief walkthrough this. Maybe it is just a matter of using the latest version of siibra.

**Comment by xgui3783** [comment]
should be fixed by https://github.com/FZJ-INM1-BDA/siibra-api/releases/tag/0.0.2
