### ISSUE TITLE
Editing landmark names sends control messages to viewer

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1017]
When editing the name of a landmark, the keys pressed are also sent to the underlying viewer which should not be the case. In particular, when entering a space for the name, the viewport will cycle. Expected behaviour: inputs are only accepted in the currently active control element.

**Comment by xgui3783** [comment]
duplicated: https://github.com/FZJ-INM1-BDA/siibra-explorer/issues/1005
