### ISSUE TITLE
'q' will hide all layers except for template

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1042]
The 'q' key is used to hide segmentations / maps. This is especially important when adding annotatinos in zoomed-in bigbrain views. However, pressing 'q' will also hide the user annotations. It would be great if user annotations are behind a different layer, and not subject to this shortcut key. They should always be shown when annotation mode is active.

**Comment by xgui3783** [comment]
Currently, the viewer will toggle all layers except for the first one. This also affects local nifti volume, for example.

A more definitive approach is to keep track of all segmentation layer(s), and toggle the visibility.

**Comment by fsdavid** [comment]
I see now, yes, I thought that list will need to update by hand. Sure I will make the change.

**Comment by xgui3783** [comment]
fixed by 2.6.0
