### ISSUE TITLE
ugly bigbrain view

### ISSUE THREAD

**Issue by AnnaHilverling** [FZJ-INM1-BDA/siibra-explorer#1122]
I wanted to work with the BigBrain in the viewer (02.12.2021) and noticed the following:
- ugly representation of the colours of the regions
- Settings: change orientation -> a white window without content appears
![grafik](https://user-images.githubusercontent.com/91078826/144461636-a780c3ed-d1db-48a6-b7dc-58062d73944a.png)

**Comment by xgui3783** [comment]
@fsdavid can you take a look?

It seems to be css/font color issue.

**Comment by fsdavid** [comment]
Thanks for the info. I'll have a look

**Comment by fsdavid** [comment]
Fixed by https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1126
