### ISSUE TITLE
consider multi point of interest (big brain, bundle atlas)

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#1135]

**Comment by dickscheid** [comment]
For some maps, coordinates representation by centroid is not appropriate. For example, for bundles, the two ends are often of interest. Also in BigBrain, as long as hemispheres are not split. 

seems there is some work in openMINDS. We need to see an example.

**Comment by xgui3783** [comment]
I checked, and am mistaken. 

- There are no known parcellation region with two points of interest in MINDS (v1)
  - the closest is a dataset -> multiple region (e.g. https://kg-editor.humanbrainproject.eu/instance/graph/minds/core/dataset/v1.0.0/4b293404-b8d3-4eba-95cd-5a66387ea428)
- There are multiple region association in siibra-configuration (see https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/blob/0d558fc38dce27c1a6e30860596da4bfc94b3592/parcellations/bundles_short.json#L77-88)
  - These are generated by us, with regex parsing

Here are some unknowns:
- in MINDS (v1), there are two `parcellationRegions`, one for each of the terminal
- how does openMINDS (v3) treat bundle atlas parcellation entity version(s)?
  - 2? one for each terminal regions?
  - 3? one for each terminal regions, one for bundle itself?
