### ISSUE TITLE
possibility to increase resolution of 2D planes in 3D view

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#1137]
We could implement predefined classes, as we have it in youtube movies: 3D view resolution: low, medium, high, very high

**Comment by xgui3783** [comment]
maybe just remove the removal of octant? (if they don't see it, they can't complain?)

**Comment by dickscheid** [comment]
This is highly difficult, and not very effective. Suggest: Not handle it. Better disable front octant removal if needed to avoid the impression of bad resolution.
