### ISSUE TITLE
[feat] filtering of connectivity datasets in siibra-explorer

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#1158]
new connectivity features in siibra explorer

**Comment by xgui3783** [comment]
- [ ] better way to query/narrow down the selection
- [ ] modality (streamline count etc)/cohort (1000brain vs HCP)/subject id (?)

**Comment by dickscheid** [comment]
as per discussion today: Introduce 3-level filter. 

1. modality: Streamline counts, streamline lengths, functional connectrivity
2. cohort: HCP, UK Biobank, 1000 brains, ...
3. matrix: average, <subject id>, ... 


In the future, 3. we might further include to restrict age range, gender, ...

**Comment by xgui3783** [comment]
fixed in 2.8.0
