### ISSUE TITLE
Include Julich-Brain Atlas as parcellation map

### ISSUE THREAD

**Issue by SBludau** [FZJ-INM1-BDA/siibra-explorer#1190]
In siibra python, Julich-Brain is a parcellation and MNI152 or colin27 is a space.

In siibra explorer inside the layer box the Julich-Brain atlas does not appear directly under parcellations but can only be selected as default parcellation via the spaces.

Shouldn't Julich-Brain also appear as a parcellation?

**Comment by dickscheid** [comment]
This is a valid question. What I suggest is to add the cytoarchitectonic maps to the list of maps in the layer selector. Currently, they are not inlcueed there since they are considered the "base layer" which is always active. But it is true that this makes them less visible.

**Comment by xgui3783** [comment]
related to #1230

**Comment by xgui3783** [comment]
fixed in 2.8.0
