### ISSUE TITLE
1um viewer positioning

### ISSUE THREAD

**Issue by ch-schiffer** [FZJ-INM1-BDA/siibra-explorer#1209]
When the 1um viewer plugin is visible and the browser window is resized, the positioning of the viewer plugin does not change correctly. In the worst case, resizing the browsers window moves the 1um viewer plugin outside of the viewport, making it unusable. The viewer plugin should maintain it's relative positioning when the browser window is resized.

**Comment by xgui3783** [comment]
this should be fixed in 2.7.5 ([release notes](https://siibra-explorer.readthedocs.io/en/latest/releases/v2.7.5/)), where the plugin window is now statically anchored in one of three positions.
