### ISSUE TITLE
[UI] if receptor only has finger print, show message "there are no profile/AR for this receptor"

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#1239]
e.g. 

```
https://atlases.ebrains.eu/viewer/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2/p:minds:core:parcellationatlas:v1.0.0:94c1125b-b87e-45e4-901c-00daee7f2579-290/r:_66981ff2::12/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIy..2j-Ye.10aGO.oHtQ~..PlA/f:siibra:features:receptor:77246f210627c711ad5adedeb83c60e3
```

on attempt to select receptor, nothing happens... this is a confusing behaviour. 

We should show a message, either before, or after clicking on the receptor "there are no profile/AR for this receptor"

**Comment by dickscheid** [comment]
I thing that in previous versions, we just didn't show the dropdown menu in case no profiles are available, just the fingerprint. Wouldn't that be a consistent behavior already?

**Comment by xgui3783** [comment]
No longer relevant as of [2.10.0](https://github.com/FZJ-INM1-BDA/siibra-explorer/releases/tag/v2.10.0) , as fingerprint & profiles are now separate features.
