### ISSUE TITLE
Typo: jugex plugin is titled "siibar-jugex"

### ISSUE THREAD

**Issue by ch-schiffer** [FZJ-INM1-BDA/siibra-explorer#1246]
See title. Just a small type in the plugin menu entry for siibra-jugex.

**Comment by xgui3783** [comment]
should be fixed in https://github.com/FZJ-INM1-BDA/siibra-jugex/pull/3/commits/be8d1e184ba668c0655da03d141ae5405d69cfd4 , and the changes will be seen when new siibra-explorer deploys

**Comment by xgui3783** [comment]
fixed
