### ISSUE TITLE
Private volume lost when changing parcellation in siibra-explorer

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#1285]
When viewing the anchoring result in siibra-explorer via VoluBA, the aligned volume is displayed on top of BigBrain space and BigBrain Isocortex parcellation. Chaning the parcellation leads to the user volume disappearing. As long as the parcellation is supported by BigBrain, the volume should be shown as e.g. comparing the alinged volume to cytoarchitectonic maps is the most interesting for the user.

From Voluba: https://github.com/FZJ-INM1-BDA/voluba/issues/142

**Comment by xgui3783** [comment]
siibra-explorer wouldn't know what to do and when. 

it is up to the plugin to listen to events and react accordingly. 

In the above usecase, voluba companion plugin should listen to parcellation changing events, and react by re-adding the layer. 

This can (probably) be done unmounting and remounting the ng-layer-tune.
