### ISSUE TITLE
Add arrows  for fine grained position changes

### ISSUE THREAD

**Issue by PolarBean** [FZJ-INM1-BDA/siibra-explorer#1300]
In a recent update siibra now has this feature when you enlarge any of the three planes:
![image](https://user-images.githubusercontent.com/38996929/230475055-26511873-b800-4ec7-84e1-41e60fdd9f00.png)
This is fantastic, but it can be hard to make small adjustments accurately. Would it be possible to add arrows so users can change position one voxel at a time?

**Comment by xgui3783** [comment]
with the ability to traverse in z direction with `<ctrl>`/`<shift>` + `[wheel]`, can we consider this issue resolved?

**Comment by PolarBean** [comment]
sounds good to me!
