### ISSUE TITLE
[data issue] Label mismatch in fsaverage jba 3.0

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-explorer#1316]
See https://github.com/FZJ-INM1-BDA/siibra-python/issues/374

**Comment by xgui3783** [comment]
Can you elaborate what is the expected behavior and what's the actual behavior?

**Comment by xgui3783** [comment]
How does this issue manifest in siibra explorer?

Name of the region appears incorrectly? Some triangles are mislabelled (should be area A, but is instead labelled area B) ?

**Comment by AhmetNSimsek** [comment]
The regions HC-Transubiculum, OP2, Entorhinal Cortex, hOc5 (possibly more) have the correct name but they are mislabeled so they appear in the wrong place.

Hartmut fixed it already and sent the correct files to the curation. A new dataset is about to be released. When it does, we will need to update the links in the Fsaverage jba3 map.

**Comment by xgui3783** [comment]
fixed as of 2.12.0 release
