### ISSUE TITLE
ctrl + scroll to go to the next slice does not work on linux machines 

### ISSUE THREAD

**Issue by PolarBean** [FZJ-INM1-BDA/siibra-explorer#1334]
Hi, 

I am running Red hat linux (Red Hat Enterprise Linux 9.1 (Plow)). The ctrl + scroll feature does not work ( I have tried several keyboards). I dont have other distros on hand but from memory I have had the same issue while running Manjaro so it may be general to linux systems. Otherwise it runs well for me. Thank you.

all the best, 

Harry

**Comment by xgui3783** [comment]
will be fixed by https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1391 and release of 2.12.4

**Comment by PolarBean** [comment]
Fantastic!

**Comment by xgui3783** [comment]
fixed by https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1389
