### ISSUE TITLE
Overlay settings reset when hidden. 

### ISSUE THREAD

**Issue by PolarBean** [FZJ-INM1-BDA/siibra-explorer#1338]
Dear Siibra team, 

Setting the appearance of the volume using the overlay works well for me. Howvever when I minimise the settings by clicking the slider icon in the top right next to the trash can icon (see screenshot), the settings reset upon being reopened. Would it be possible to make the settings unchanged when hidden and reopened?

Thank you in advance, 

Harry
![image](https://github.com/FZJ-INM1-BDA/siibra-explorer/assets/38996929/a50b54dd-d728-4370-b61b-60eb41c735ff)

**Comment by xgui3783** [comment]
This might have been a feature requested before, but I was very coincidentally working on this in the last two days. 

the library responsible for the underlying layer turning, https://github.com/xgui3783/ng-layer-tune latest commit address *exactly* this issue:

https://github.com/xgui3783/ng-layer-tune/commit/a1406d662b2acdd06c800e0c84eb62ececc67fa4

You can see it in action here: https://ng-layer-tune.netlify.app/

The feature can be rolled out next bugfix release of siibra-explorer

**Comment by PolarBean** [comment]
haha how lucky! Great stuff, looking forward to it

**Comment by PolarBean** [comment]
This is maybe outside the scop of this issue, but often once the setttings for a volume are set people want to interactively change the opacity to compare the volume to the template. So while other settings are relatively static, thew user may want to constantly adjust opacity. Is there scope for keeping opacity visible while other settings are visible or do you think this is too specific a use case?

**Comment by xgui3783** [comment]
welp this is embarrassing. 

The sliders state are perserved, but the colormap selection is not... 

It will have to arrive in the next bugfix release

**Comment by PolarBean** [comment]
nice! thanks for the update. A big improvement :)

**Comment by xgui3783** [comment]
fxied by https://github.com/FZJ-INM1-BDA/siibra-explorer/releases/tag/v2.11.3

**Comment by xgui3783** [comment]
> This is maybe outside the scop of this issue, but often once the settings for a volume are set people want to interactively change the opacity to compare the volume to the template. So while other settings are relatively static, the user may want to constantly adjust opacity. Is there scope for keeping opacity visible while other settings are hidden or do you think this is too specific a use case?

Can you file a separate issue (more of a FR) for this one? so we can keep it on the radar.
