### ISSUE TITLE
Rat tracer connectivity dataset link and description does not show up

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-explorer#1355]
Note: Siibra-python can find the ebrains pages (as a doi) and id.
https://doi.org/10.25493/S0DK-2DK

**Comment by xgui3783** [comment]
shows up for me:
<img width="1280" alt="Screenshot 2023-06-19 172227" src="https://github.com/FZJ-INM1-BDA/siibra-explorer/assets/19381783/2ade67ee-ad85-496f-8d3b-2c37700ea7a5">
