### ISSUE TITLE
[enhancement] Display subject names on connectivity data for datasets the subject name is important

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-explorer#1356]
Currently, this is only the case for tracer connectivity data for rat atlas. This is a user request.

**Comment by xgui3783** [comment]
is there a preferred layout how it should be done? or just that it should be shown _somewhere_ ?

**Comment by AhmetNSimsek** [comment]
Preferably, next to the word `subject` or under it. The names will be updated so assume that it might be 2 lines long.

**Comment by xgui3783** [comment]
fixed by https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1358 , will be live on  next minor update

**Comment by xgui3783** [comment]
fixed as of 2.12.0 release
