### ISSUE TITLE
Remember user acceptance of privacy policy

### ISSUE THREAD

**Issue by PolarBean** [FZJ-INM1-BDA/siibra-explorer#1361]
Every time I view the siibra explorer tool i get a popup asking me to accept the privacy/cookie policy. Would it be possible to have a cookie that remembers the users choice for this popup? 
All  the best, 
Harry

**Comment by xgui3783** [comment]
fixed by b09939dc295b00714644c3dd4dbd52fda4821a6f (deployment will follow shortly)
