### ISSUE TITLE
When opacity is changed default colormap changes to grayscale from magma

### ISSUE THREAD

**Issue by PolarBean** [FZJ-INM1-BDA/siibra-explorer#1390]
When loading a volume if one changes the opacity (with the menu either open or in its preview state) the colormap switches from magma to grayscale. 

replication: https://interactive-viewer.apps.hbp.eu/#/a:juelich:iav:atlas:v1.0.0:2/t:minds:core:referencespace:v1.0.0:265d32a0-3d84-40a5-926f-bf89f68212b9/p:minds:core:parcellationatlas:v1.0.0:05655b58-3b6f-49db-b285-64b5a0276f83/rn:f255401/@:0.0.0.-W000..2_Q5ui.2-9bFF.-C_vw._E3bw..mJN..2L7M.AIlZ.34-H..2s2/x-overlay-layer:precomputed:%2F%2Fhttps:%2F%2Fdata-proxy.ebrains.eu%2Fapi%2Fv1%2Fbuckets%2Fd1-d2-expression%2Fd1_ng

**Comment by xgui3783** [comment]
the magma colormap is set via `meta.json`'s  `override.customShader`, I presume?

This is an interaction I did not account for. I will create a fix in the coming release. 

I should mention that, as mentioned in https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1348#issuecomment-1658904430 , one of the limitation is that custom shader cannot be controlled by the widget (except for opacity). 

we will update the component to reflect this.

**Comment by PolarBean** [comment]
I don't believe the issue is related to meta.json, I have experienced this on volumes where meta.json is not set. to illustrate this I have removed meta.json from the above example and the behaviour persists.

**Comment by xgui3783** [comment]
I stand corrected. 

I believe I know the reason: inconsistent default. In siibra-explorer, we add the layer with magma as default colormap. But on interaction with ng-layer-tune, default is greyscale. 

I would like to set magma to be default everywhere, if there is no objections.

**Comment by xgui3783** [comment]
will be fixed by https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1391 and release of 2.12.4

**Comment by PolarBean** [comment]
Magma is my favourite as well! Fantastic thank you for the fix :)

**Comment by xgui3783** [comment]
fixed by [release of 2.12.4](https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1389)
