### ISSUE TITLE
On region selection change, tracing connectivity does not show the data

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-explorer#1392]
Steps to reproduce:
- Select rat atlas
- Select a region (Ventral orbital area) (subjects with prefix "VO")
- Select connectivity and TracingConnectivity
- Change region from search (Parietal association cortex, posterior area) (subjects with prefix "PtP")
- The tracing connectivity data cannot be found at all

Current workaround:
- Select another connectivity
- Reselect tracer connectivity

**Comment by xgui3783** [comment]
won't fix

waiting for plotly implementation
