### ISSUE TITLE
Selection of 1micron sections resets view

### ISSUE THREAD

**Issue by JThoennissen** [FZJ-INM1-BDA/siibra-explorer#1404]
When selecting a 1micron section in BigBrain template the view is reset to the center instead of keeping the current view.

I think you are already aware of this but I couldn't find a corresponding issue, so I added it 🙂

**Comment by xgui3783** [comment]
fixed by https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1420

will be in prod in next release
