### ISSUE TITLE
Long loading times for BigBrain features?

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1413]
A user reported: "Bigbrain features anchored to regions takes a very long time. Not clear what it is doing."  To be verified.

**Comment by xgui3783** [comment]
addressed by [850fb08](https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1416/commits/850fb086dc5e5700413a52ec7bf8da06eeeac149)
