### ISSUE TITLE
Keep 2D 1 micron section available while plane sweeping in planar view 

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1415]
When opening a 2D section (e.g. in BigBrain) in maximized planar view (here: coronal), the mini navigator window is very helpful to inspect previous / subsequent sectional views. When going forth and back, it would be highly desirable to keep the 1 micron section in the stack. As implemented currently, it will disappear an require the user to go back to 4-pane view and search again.

Related to this, it would be great if the spatial search worked in 2D sectional views, so that sections could be discovered also by sweeping planar views.

**Comment by xgui3783** [comment]
related to #1404

**Comment by xgui3783** [comment]
fixed by #1420 

will be in prod in next release
