### ISSUE TITLE
Siibra shows all white after the first visit on Firefox

### ISSUE THREAD

**Issue by PolarBean** [FZJ-INM1-BDA/siibra-explorer#1427]
![image](https://github.com/FZJ-INM1-BDA/siibra-explorer/assets/38996929/ba9629e4-38ea-4502-9765-1c49a53c139f)
For some reason when revisiting after an initial load it shows all white. The console shows the following errors 
![image](https://github.com/FZJ-INM1-BDA/siibra-explorer/assets/38996929/706accc6-4dfe-45cd-b782-1f662b58b67f)

This has been replicated in Firefox on windows and linux  but it does not occur on Chrome.

**Comment by xgui3783** [comment]
cannot seem to reproduce with W11Home Firefox 118.0.2 (64-bit)

which version of firefox are you using?
