### ISSUE TITLE
Cannot select some regions in ICBM 2009c Nonlinear Asymmetric

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#394]
Some region names in "ICBM 2009c Nonlinear Asymmetric" is not selectable and searchable (region names looks like "jubrain mni152 v18 right#13"). For selection problem caused by "#" (like labelIndexId) in the name.

**Comment by xgui3783** [comment]
data issue, cannot label was not defined in hierarchy/xml, so cannot parse the label.
