### ISSUE TITLE
[bug] cannot instantiate two `connectivity-browser` at the same time

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#605]
as of d274c93ce38f3f1e1929da300235d1f8b62d3dcf or 055118579a26ad9e7454105f0d934d681f8cad00

to reproduce:

1/ insert the following code in any template:

```html
    <connectivity-browser>
    </connectivity-browser>
    <connectivity-browser>
    </connectivity-browser>
```

expected behaviour: two connectivity browser renders

actual behaviour: only the first connectivity browser render

attached: DOM tree
![Screenshot from 2020-07-21 19-21-33](https://user-images.githubusercontent.com/19381783/88086386-963fab80-cb87-11ea-9823-10d666bde5ad.png)

**Comment by fsdavid** [comment]
Fixed
