### ISSUE TITLE
[bug] in connectivity mode, change parcellation does not show colourmap

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#613]
as of f681e9c

steps to reproduce:

0/ goto /, select human multilevel, select mni152
1/ select any region, go to connectvity panel, turn on `apply map to viewer`
2/ switch parcellation (e.g. to short bundle)

expected behaviour: new map loads with the correct colour map

actual behaviour: new map does not load

**Comment by xgui3783** [comment]
issue persist/returned as of c4e316a

**Comment by xgui3783** [comment]
addressed by #644 , but requires e2e & refactoring

**Comment by fsdavid** [comment]
Fixed
