### ISSUE TITLE
[bug]: switching template when connectivity browser is open leads to unstable behaviour

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#639]
as of 79a37fe

steps to reproduce:

0/ go to /, select human multilevel, select mni152 template space
1/ select any region (hoc1, eg), open connectivity browser
2/ switch template to colin 27
3/ select any region (fp1, eg)

expected behaviour:

pmap shown

actual behaviour:

max pmap shown

4/ toggle connectivity accordion

expected beahviour:

connectivity widget shown, colour map applied

actual behaviour:

only white color map shown, connectivity widget not shown. 

possibilty related to #605

**Comment by xgui3783** [comment]
resolved as of a673bc2 

still needs e2e to prevent regression

**Comment by fsdavid** [comment]
Fixed
