### ISSUE TITLE
[Bug] Explore in other templates restores viewer zoom

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#688]
steps to reproduce:

0/ go to /, select human multilevel, select mni152 template space
1/ select any region and expand "Explore in other templates"
2/ Explore region in any template

expected behavior:
zoom should be the same

actual behavior:
zoom restores

**Comment by xgui3783** [comment]
wait until big brain has hemisphere'ed ROI defined.

**Comment by xgui3783** [comment]
explore in other template has been removed.
