### ISSUE TITLE
[bug] connectivity browser cannot be lazy loaded / does not update on input changes

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#698]
as of 213cd1a7da58af6d6e8aae5d484d58dfb88b4c46

1/ cannot be lazy loaded

to reproduce:

- go to /, select human multi level atlas, load mni152
- select hoc1
- click `connectivity` expansion panel **once**

expected beahviour: opens panel

actual behaviour: panel opens, but connectivity component has no content

2/ when input changes, does not update color map

to reproduce:

- go to /, select human multilevel, load mni152
- select hoc1
- click `connectivity` until the panel is expanded (twice)
- go to region finder field, clear text and search and select hoc3

expected behaviour: color map applied
actual behaviour: color map not applied

**Comment by fsdavid** [comment]
@xgui3783 Is this still actual? Can not reproduce.

**Comment by xgui3783** [comment]
to provide some context, you will have to checkout 213cd1a7da58af6d6e8aae5d484d58dfb88b4c46

lazy rendering was added via the `matExpansionPanelContent` directive:

https://github.com/HumanBrainProject/interactive-viewer/blob/213cd1a7da58af6d6e8aae5d484d58dfb88b4c46/src/ui/nehubaContainer/nehubaContainer.template.html#L332-L335

But because of the issue, the change is reverted by https://github.com/HumanBrainProject/interactive-viewer/commit/a557eb036adf9ddeb52f45a4eae2bff4821f1267#diff-5194777414a8d439fbc25c9094dfca145f65dff4b04b5bfe59fa1c192ef1c74a

The issue should still be addressed

**Comment by xgui3783** [comment]
This can wait until next bugfix patch. not for immediate release, IMO

**Comment by fsdavid** [comment]
Not relevant
