### ISSUE TITLE
[Bug] Receptors chart does not contain all the Fingerprint names

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#759]
steps to reproduce:
1. Go to: https://interactive-viewer-next.apps-dev.hbp.eu/?templateSelected=MNI+152+ICBM+2009c+Nonlinear+Asymmetric&parcellationSelected=Cytoarchitectonic+Maps+-+v2.4&cRegionsSelected=%7B%22ICBM152_V24_RIGHT_NG%22%3A%22V%22%7D&cNavigation=0.0.0.-W000..2_ZG29.-ASCS.2-8jM2._aAY3..BSR0..gzre.2Ac40%7E.byIw..1jtG
2. Expand regional features
3. Click on: Density measurements of different receptors for Area PFcm (IPL) [human, v1.0]
4. Scroll down and expand "Receptor density measurement"

expected behavior:
The diagram should contain all the Fingerprint text

actual behavior:
One of the fingerprints text is "Missing superscript or subscript argument"

**Comment by xgui3783** [comment]
fixed by https://github.com/FZJ-INM1-BDA/kg-dataset-previewer/commit/678793049801a179da5ed3e401e5d3d79ea4bd99

I will leave the issue open, as this is a data issue, and we need to coordinate with Lyuba (who updated the receptor data), to check if any errors still exist

**Comment by xgui3783** [comment]
can no longer reproduce

feel free to reopen if the issue persist
