### ISSUE TITLE
[Refactor] As new dataset view is on sidebar, explore pinned datasets should also displayed on sidebar 

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#763]
Steps to reproduce:

1. Go to: https://interactive-viewer-next.apps-dev.hbp.eu/
2. Select "Multilevel Human Atlas"
3. Pin any dataset
4. Expand pinned datasets
5. Click on the dataset

expected behavior:
Dataset appears on the sidebar

actual behavior:
Dataset appears on the dialog view

**Comment by xgui3783** [comment]
Not for current release

**Comment by xgui3783** [comment]
pinned datasets have been removed. no longer relevant.
