### ISSUE TITLE
[bug] Number of the filters is incorrect in regional features

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#841]
to reproduce:

1/ go to human multilevel
2/ Select region `Area 6mp (SMA, mesial SFG) (right hemisphere)`
3/ Expand regional features

expected behaviour:
Filter feature number should be equal to selectable filters 

actual behaviour:
Filter feature number is `2` and actually there is single selectable filters 

![image](https://user-images.githubusercontent.com/26521731/104933173-dce05800-59a8-11eb-89ce-ecea8611c339.png)

**Comment by xgui3783** [comment]
This is expected behaviours. 

in the screenshot above, the selectable is a modality. Feature(s)  are synonymous to datasets. Perhaps we should make it more clear, like renaming `features` to `data features` ? @dickscheid

**Comment by fsdavid** [comment]
> This is expected behaviours.
> 
> in the screenshot above, the selectable is a modality. Feature(s) are synonymous to datasets. Perhaps we should make it more clear, like renaming `features` to `data features` ? @dickscheid

Agree

**Comment by fsdavid** [comment]
Demo: https://con-line.okd-dev.hbp.eu/
