### ISSUE TITLE
"Navigate to region" button brakes line on Mac's full screen chrome window

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#842]
to reproduce:

1/ go to human multilevel
2/ Select any region

Expected behaviour: 
Navigate button should be at the same line as the pin button

Actual behaviour:
![image](https://user-images.githubusercontent.com/26521731/104936111-62193c00-59ac-11eb-8117-35490af7b966.png)

**Comment by xgui3783** [comment]
UI redesigned. No longer relevant.
