### ISSUE TITLE
[chore] user annotation - use built-in from NG

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#886]

**Comment by xgui3783** [comment]
We should probably collect feedbacks/bug reports in this thread eventually. 

here is one:

(I don't exactly remember how to reproduce, but I think I moved from ICBM152 -> BigBrain -> ICBM152, and the annotations refuses to show)

https://user-images.githubusercontent.com/19381783/115042809-1d7e3d80-9ed4-11eb-85cb-a085c13c8cc0.mp4

error in log:

```
main.js:236 ERROR TypeError: Cannot read property 'layer' of undefined
    at bq.addAnnotationOnViewer (main.js:2893)
    at bq.toggleAnnotationVisibility (main.js:2893)
    at main.js:2893
    at nl (main.js:642)
    at r (main.js:642)
    at HTMLButtonElement.<anonymous> (main.js:2170)
    at t.invokeTask (main.js:1294)
    at Object.onInvokeTask (main.js:1033)
    at t.invokeTask (main.js:1294)
    at e.runTask (main.js:1294)
```

**Comment by fsdavid** [comment]
@xgui3783 Thank you very much for the video. Yeah, I see the problem, there is no annotation layer added at all, as it depends on the bottom sheet, and changing templates is not supported yet, it is quite buggy. I'll look at the problem

**Comment by xgui3783** [comment]
Found another bug. I know it's at early stage, but just wanted to catalogue the bug, so it won't get lost.

Bottomsheet doesn't close.

I have no idea how to recreate this.

https://user-images.githubusercontent.com/19381783/115057335-368eea80-9ee4-11eb-87e5-15cf317a806a.mp4

**Comment by fsdavid** [comment]
@xgui3783 Thanks. I will try to find but if it but before, we change the approach I hope the bug will disappear :)

**Comment by xgui3783** [comment]
Per discussion:

TODO

- [ ] add both context menu and annotation mode
- [ ] move annotation mode to "my collection"
- [ ] allow mouseover to be emitted
