### ISSUE TITLE
[FR] migrate to use brainscapes-api instead of existing backend

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#889]
endpoints to be migrated:

- [x] atlas (https://github.com/HumanBrainProject/interactive-viewer/issues/908)
- [x] template (https://github.com/HumanBrainProject/interactive-viewer/issues/908)
- [x] parcellation (https://github.com/HumanBrainProject/interactive-viewer/issues/908)
- [x] region (https://github.com/HumanBrainProject/interactive-viewer/issues/908)
- [x] fetch regional datasets (dependency: https://github.com/FZJ-INM1-BDA/siibra-python/issues/21)
- [x] regional prob map (one's provided in siibra-python does not work, because 1/ cors, 2/ incorrect xyzt_header 3/ datatype) (018a084c0144acc0657430643186749cc844a122)
- [x] connectivity (https://github.com/HumanBrainProject/interactive-viewer/issues/909)
- [ ] #976
- [x] detailed regional features (receptor density) (https://github.com/HumanBrainProject/interactive-viewer/issues/910)
- [ ] #975

**Comment by xgui3783** [comment]
perhaps we should break this card into smaller cards?

- one for altas/template/parcellation/regoin
- one for connectivity
- one for region in different template
- one for regional features
?

**Comment by fsdavid** [comment]
Yes. i agree. I will do that

**Comment by xgui3783** [comment]
@fsdavid I have some time, I can also help. if/when you create the issue, link it to this card under the correct category, eh?

**Comment by xgui3783** [comment]
@fsdavid I have created issues as discussed

I merged `region diff tmpl` with `atlas / tmpl / parc / region`, seeing that they are very much connected

can you assign youself the card(s) you are currently working on?

**Comment by fsdavid** [comment]
Currently, I've started working on `atlas / tmpl / parc / region` would like to change the approach a little bit (load them after selection but I'm not sure yet what problems I will meet.
