### ISSUE TITLE
[FR] display connection strength in perspective view via edge diameter

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#892]
Display connectivity lines in 3D.

- Line diameter and color should depend on connection strength

**Comment by xgui3783** [comment]
@dickscheid to ask those who generates connectivity visualising on how thresholding are usually done

**Comment by xgui3783** [comment]
probably out of scope at this stage. 

closing issue.

feel free to reopen the issue if you feel this issue becomes relevant again.
