### ISSUE TITLE
[FR] Have a quick tour to explore the viewer on a first visit.

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#899]
Create a quick tour to explore the viewer on a first visit.

**Comment by xgui3783** [comment]
@fsdavid can you add URL for the preview?

also, are you expecting to raise a PR? We can get code review done, too, while we wait for Timo.

**Comment by fsdavid** [comment]
Sure, you can find the demo here: https://quick-tour-demo.okd-dev.hbp.eu/
maybe wait for the first look at least? After the last review, there are a lot of changes :) also, I take out almost all logic.

**Comment by fsdavid** [comment]
You can find a new version of the quick tour here:
https://quick-tour-demo.okd-dev.hbp.eu/

Now it is free to use the viewer while touring. Now it is a little bit smarter than the last one, e.g. in "layer selector", "nebula navigation" and "region sidebar" it changes tip automatically when panels are opened or closed (but it does not go to the next step automatically).

**Comment by xgui3783** [comment]
feedback:

from TD: 
- eye icon no longer exist
- clickable progress bar
