### ISSUE TITLE
[FR] migrate connectivity to brainscape api

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#909]
main issue: https://github.com/HumanBrainProject/interactive-viewer/issues/889

**Comment by fsdavid** [comment]
Waiting for the issues to be fixed: 
https://jugit.fz-juelich.de/v.marcenko/brainscapes-api/-/issues/23
https://jugit.fz-juelich.de/v.marcenko/brainscapes-api/-/issues/22
