### ISSUE TITLE
[FR] support point clouds from KG

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#942]
FR from @Majpuc

fetch and show point clouds in viewer from KG dataset such as https://search.kg.ebrains.eu/instances/Dataset/c2f276c1-5deb-49e5-b9ad-6fbc0d478cba

**Comment by Majpuc** [comment]
@xgui3783 Did you have a chance to look at this?

**Comment by xgui3783** [comment]
Not yet.

I suspect this is a good candidate to be implemented as a data feature as a part of [siibra-python](https://github.com/FZJ-INM1-BDA/siibra-python) . 

pinging @dickscheid @marcenko 

(siibra-explorer is pivoting to use siibra-python for fetching metadata of atlases and all of the features)

**Comment by AhmetNSimsek** [comment]
The addition of pointset data type is tracked here https://github.com/FZJ-INM1-BDA/siibra-python/issues/322 and with the branch https://github.com/FZJ-INM1-BDA/siibra-python/tree/addPointsetDatafeature

**Comment by xgui3783** [comment]
partial drag-drop support available since v2.14.0 see screencast below:

https://data-proxy.ebrains.eu/api/v1/buckets/test-sept-22/dragdropptcloud.mp4

**Comment by xgui3783** [comment]
closed as complete for now, since the feature is generally available
