### ISSUE TITLE
Maps missing in viewer

### ISSUE THREAD

**Issue by ch-schiffer** [FZJ-INM1-BDA/siibra-explorer#983]
I was informed that some cytoarchitectonic maps, which were made available in the viewer some time ago, are now missing from the viewer.

For example, I noticed that the following areas are missing (there might be more):

- LGB ([KG](https://search.kg.ebrains.eu/instances/d0c36f4a-91a8-4885-880d-f2896f5c54cf),  [viewer](https://interactive-viewer.apps.hbp.eu/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:a1655b99-82f1-420f-a3c2-fe80fd4c8588/@:0.0.0.-W000.._YYCk.2-DuEy.-5_Ew.2_VOZ4..4a_0..1GeRe~.DrL4~.RjPd~..Lv_))
- MGB ([KG](https://search.kg.ebrains.eu/instances/6e3ca542-af3b-4869-b3ec-38986c4b1395), [viewer](https://interactive-viewer.apps.hbp.eu/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:a1655b99-82f1-420f-a3c2-fe80fd4c8588/p:juelich:iav:atlas:v1.0.0:7/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIx..k5M~.DeI3~.SH8X~..C9L))

Also, the viewer links do not show the correct layer anymore (the used to show cyto maps, now they show layer maps).
However, even when selecting the cyto layer manually, the mentioned areas are gone completely (not visible in the section view, not listed in the region hierarchy).
My guess would be that some conversion from the "old" viewer went wrong and missed these areas.

**Comment by xgui3783** [comment]
this is related to https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/issues/1

regions absent in the region hierarchy would be missing in the new release of atlas viewer too.

it seems, that at least MGB is represented, and the super structure of LGB is present in the form of `CGL (Metathalamus)`

**Comment by ch-schiffer** [comment]
The existing CGL entry seems to correspond only to the super structure of CGL, not the sub-parcellations which exist (currently) only for BigBrain.
I am not sure if I can just add new entries to the parcellation definition files (https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/tree/develop/parcellations). I am also not sure which branch I could make changes on (there are so many).  @dickscheid Can you comment on this?

**Comment by xgui3783** [comment]
hmm, the parcellaiton definition file is the one that we obtained from Hartmut. 

Whilst there isn't a problem to have regions with greater granularity defined (in this example, Iam1-6 in CGL), the provenance and multiple sources of truth will can become a headache in the future.

I wonder if we could have hartmut update the region hierarchy (even though it makes no sense in MNI152 or Colin).

would love to hear your opinion @dickscheid

**Comment by xgui3783** [comment]
@ch-schiffer 

I have made some changes, which are live on the staging URL

- LGB ([viewer link](https://interactive-viewer-staging.apps.hbp.eu/?templateSelected=Big+Brain+%28Histology%29&parcellationSelected=Cytoarchitectonic+Maps&cNavigation=0.0.0.-W000.._YYCk.2-DuEy.-5_Ew.2_VOZ4..4a_0..1GeRe%7E.DrL4%7E.RjPd%7E..Lv_))
- MGB ([viewer link](https://interactive-viewer-staging.apps.hbp.eu/?templateSelected=Big+Brain+%28Histology%29&parcellationSelected=Cytoarchitectonic+Maps+-+v2.4&cNavigation=0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIx..k5M%7E.DeI3%7E.SH8X%7E..C9L))

Can you double check this is as expected?

If so, I will release it to production.

**Comment by ch-schiffer** [comment]
The maps now look as expected. I noticed that the backreference to the KG (regional features) are not working though. Also, the links shown in the KG cards (e.g. [this one](https://interactive-viewer.apps.hbp.eu/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:a1655b99-82f1-420f-a3c2-fe80fd4c8588/p:juelich:iav:atlas:v1.0.0:3/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7LIx..k5M~.DeI3~.SH8X~..C9L) from [MGB](https://search.kg.ebrains.eu/instances/6e3ca542-af3b-4869-b3ec-38986c4b1395)) still link to the cortical layer level instead of the cyto map layer. Was there a change in how links are constructed which could lead to incompatibility of "old" links?

**Comment by xgui3783** [comment]
> I noticed that the backreference to the KG (regional features) are not working though.

This unfortunately cannot be remedied until we properly add the regions in siibra-configration/siibra-python.

I recommend that we follow https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/issues/1 for the progress.

>  Also, the links shown in the KG cards (e.g. this one from MGB) still link to the cortical layer level instead of the cyto map layer. 

This is because I have not yet pushed the prod server yet. I just pushed it to production server, and the links on KG card should work in 10 minutes or so.

**Comment by xgui3783** [comment]
fixed in release 2.4.3
