### ISSUE TITLE
[bug] connectivity browser cannot select different data source

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-explorer#991]
to reproduce:

use dev (b13cb82) 

0/ go to / , select multilevel human atlas, select region, select connectivity
1/ try to select a different data source

expected behaviour:

data source can be selected
click on region results in navigation to the region

actual behaviour:

no new datasource available
click on region does not result in navigation in region
error in console

**Comment by fsdavid** [comment]
`data source can be selected` - You mean that on connected region click, selected region should be changed automatically? if so it is more feature request I guess.

`click on region does not result in navigation in region` - this issue was valid for first region only and it should be resolved now.

**Comment by xgui3783** [comment]
> data source can be selected - You mean that on connected region click, selected region should be changed automatically? if so it is more feature request I guess.

No, there are only 1 data data source, namely `Average streamline counts from diffusion imaging, 1000BRAINS cohort`

On attempt to select another, there is a error logged in console.

it probably is an issue with siibra-api, but it should be:

- filed with siibra-api, and tracked here
- handled graciously, preferably show the data sources that are not malformed.

**Comment by fsdavid** [comment]
Do see multiple sources on Julich brain 2.9 or 1.18?
![image](https://user-images.githubusercontent.com/26521731/130406178-2f700116-ffdf-462e-9b89-0cfe40000b85.png)

**Comment by xgui3783** [comment]
for v1.18, all are working as intended.

for v2.9, on attempt to change data source, only 1 source is available. 

Additionally, **after** attempt to change data source, single click to navigate to region no longer works

for dev build: https://siibra-explorer.apps-dev.hbp.eu/dev/

**Comment by xgui3783** [comment]
fixed by #993
